---
title: "Client Report - Project 1"
subtitle: "Course DS 250"
author: "Nathan Lunceford"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import altair as alt
import numpy as np

from IPython.display import Markdown
from IPython.display import display
from tabulate import tabulate
```


## Elevator pitch

_In this project, we worked with a names database and compared the usage of different names over time._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
dat = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

__Highlight the grand questions__

## GRAND QUESTION 1

__How does your name at your birth year compare to its use historically?__

_When I was born in the year 2002 the usage of my name was approaching its peak. The data shows that the name "Nathan" was not very popular from the year 1910 to about 1967. At around the year 1967, the name "Nathan" saw a sharp increase in usage which continued to increase until about 2005 when it saw its peak and began to decline._

```{python}
#| label: GQ1
#| code-summary: Read and format data
# Include and execute your code here
names = pd.read_csv('names_year.csv')

nathan = names.query('name == "Nathan"')

birthYearDf= pd.DataFrame({'year': [2002]})
birthYearLine = alt.Chart(birthYearDf).mark_rule(color="red").encode(x = "year")

birthYearLabel = alt.Chart(birthYearDf).mark_text(
    text='Birth of Nathan Lunceford (2002)',
    align='left',
    baseline='middle',
    dx=10,
    dy=250,
    color= 'red'
).encode(
    x='year',
    y=alt.value(0)  # adjust label position
)

chartNathan = (alt.Chart(nathan, title = 'Name of Nathan over the years')
  .encode(
    x = alt.X('year', axis = alt.Axis(format= 'd', title= 'Year')),
    y = alt.Y('Total', axis= alt.Axis(format= 'd', 
                title='Children with the name Nathan', ))
    )
  .mark_line()
)

chart = chartNathan + birthYearLine + birthYearLabel
chart

```

_The data shows that I was born near the peak of naming babies the name "Nathan"._


## GRAND QUESTION 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_If I talked to someone named Brittany on the phone I would guess that she was around 33 years old. The ages I would not guess are 40 or older and 23 or younger._

```{python}
#| label: GQ2
#| code-summary: Read and format data
# Include and execute your code here

# Load Dataset
names = pd.read_csv('names_year.csv')

# Query Brittany
brittany = names.query('name == "Brittany"')

# Chart Brittany
chartBritrany = (alt.Chart(brittany, title = 'Name of Nathan over the years')
  .encode(
    x = alt.X('year', axis = alt.Axis(format= 'd', title= 'Year')),
    y = alt.Y('Total', axis= alt.Axis(format= 'd', 
                title='Children with the name Brittany' ))
    )
  .mark_line()
)

# Peak Brittany year Dataframe
year1990Df = pd.DataFrame({'Year': [1990]})
year1990Line = alt.Chart(year1990Df).mark_rule(color="red").encode(x = "Year")

# Year 1990 Label
year1990LineLable = alt.Chart(year1990Df).mark_text(
    text='Year where most Brittanys were born (1990)',
    align='left',
    baseline='middle',
    dx=10,
    dy=10,
    color= 'red'
).encode(
    x='Year',
    y=alt.value(50)  # adjust label position
)

# Final Chart
chart = chartBritrany + year1990Line + year1990LineLable
chart





```

_This data shows a clear peak in the name "Brittany". The name "Brittany" peaked in 1990 and fell pretty sharply as the year approached 2000._


## GRAND QUESTION 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_From this data, I saw that the name "Mary" has almost always been the most popular of the four names except for several brief periods in the 60s, 70s, and 80s when the name "Paul" surpassed "Mary" in popularity. The names "Martha" and "Peter" were less popular between 1920-2000. A clear trend I noticed is that the data shows that all four names had a peak around 1950-1960._

```{python}
#| label: GQ3
#| code-summary: Read and format data
# Include and execute your code here
data = pd.read_csv('names_year.csv')

# Filter data for desired names
names = ['Mary', 'Martha', 'Peter', 'Paul']
filtered_data = data[data['name'].isin(names) & (data['year'] >= 1920) & (data['year'] <= 2000)]

# Create final chart
chart = (alt.Chart(filtered_data, title='Names over the years')
         .encode(x=alt.X('year', axis=alt.Axis(format='d', title='Year')),
                 y=alt.Y('Total', axis=alt.Axis(format='d', title='Children with the name')),
                 color=alt.Color('name', title='Name'))
         .mark_line())

chart

```

_"Mary" is shown to be the most poplular name compared to "Martha", "Paul", and "Peter"._


## GRAND QUESTION 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

_I chose the movie Batman (1943) where the main character is Bruce Wayne. The data shows a clear uprising in the name "Bruce" after the movie was released but I am not so sure that the release of Batman (1943) had anything to do with it. The graph shows a consistent increase in usage of the name "Bruce" from 1910 forward which was before the release of Batman (1943). However, the graph shows a sharper increase in the usage of the name "Bruce" after the release of Batman (1943). I conclude that the name "Bruce" was already rising in popularity and the release of Batman (1943) only increased the popularity of an already popular name._

```{python}
#| label: GQ4
#| code-summary: Read and format data
# Include and execute your code here
# Load data
data = pd.read_csv('names_year.csv')
data

#%%
# Filter data for desired name
bruce = data.query('name == "Bruce"')

# bruce = data[data['name'] == "Bruce"]
# bruce

# Create Bruce charts
bruceChart = (alt.Chart(bruce, title='Name of Bruce over the years')
         .encode(x=alt.X('year', axis=alt.Axis(format='d', title='Year')),
                 y=alt.Y('Total', axis=alt.Axis(format='d', title='Children with the name Bruce')),
                 )
         .mark_line())


# Create an lable dataframe for when the first Batman movie came out
batman1943Df= pd.DataFrame({'year': [1943]})

batman1943Line = alt.Chart(batman1943Df).mark_rule(color="red").encode(x = "year")


batman1943LineLabel = alt.Chart(batman1943Df).mark_text(
    text='First Batman movie comes out (1943)',
    align='left',
    baseline='middle',
    dx=10,
    dy=10,
    color='red').encode(
    x='year',
    y=alt.value(0)  # adjust label position
)

# Final chart
chart = bruceChart + batman1943Line + batman1943LineLabel
chart

```

_The data shows that the usage of the name "Bruce" peaked around 1955 which was after the release of Batman (1943)._


## APPENDIX A (Additional Python Code)

```python
#paste other your code from your python file (.py) here
```
